# Create a LoadBalancer and attach the Security group and Subnets
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      #VpcId: !ImportValue VPC-ID
      IpAddressType: ipv4
      Name: !Join ['-', [!Ref "AWS::StackName", "ALB-public"]]
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue Public-ALB-SG-ID
      Subnets:
        - !ImportValue PublicSubnetA
        - !ImportValue PublicSubnetB
      Type: application
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - RedirectConfig:
            Path: "/#{path}"
            Port: 443
            Protocol: "HTTPS"
            Query: "#{query}"
            StatusCode: HTTP_301
          Type: redirect
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
Outputs:
  LoadBalancer:
    Description: A reference to the security group for load balancers
    Value: !Ref LoadBalancer
    Export:
      Name: Public-ALB-ID