# To create VPC
AWSTemplateFormatVersion: 2010-09-09
Description: Setting up VPC to deploy AWS services, microservices in private network.
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
  # Create IGW for VPC:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  # Attach IGW:
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway